
# Site settings
title: Curve Balancing 
email: karynarmr33@gmail.com	
description: "Balancing learning curves, life's curve balls, curves of the banked track, and the curves of my ass.  All on roller skates."

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: karynarmr
github_username:  karynarmr	

# Build settings
markdown: kramdown
highlighter: false