# Site settings
title: My Jekyll blog
email: karynarmr33@gmail.com	
description: > # this means to ignore newlines until "baseurl:"
  My coding journey began as I struggled to learn how to manage people.  Troubleshooting websites is way less messy.  Rigth?	
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: karynarmr
github_username:  karynarmr	

# Build settings
markdown: kramdown
highlighter: false